Enabled local build hooks.
britishcouncil/platformsh-cli pull request #7
Opened 2019-02-15 11:10 UTC by graber-1

Also aded a few smaller related improvements.

2019-02-18 11:48 UTC, gmahe approved these changes
This works and it is now considering build hooks!
 For the code @vincenzo would have more experience to review it.

2019-02-19 17:04 UTC, vincenzo requested changes

2019-02-19 17:04 UTC, vincenzo commented on src/Command/Drupal/DrupalDeployCommand.php
> +        $this->output->writeln('Running post-build hooks adapted to local environment.');
I've also tested this now. It works fine, as far as I can tell. 
The only thing I would ask for is to keep the messaging consistent and change the line above to something on the same pattern as this: https://github.com/britishcouncil/platformsh-cli/blob/12d49235288e9fcd99ff5875b1a446c37ac468c1/src/Command/Drupal/DrupalDeployCommand.php#L369

2019-02-20 09:22 UTC, vincenzo approved these changes

2019-02-20 09:25 UTC, vincenzo commented
Merging this and refreshing the `__stable` tag, so that by running `platform-update` inside the VM you may get the new version.

2019-02-20 09:26 UTC, merged